### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by xympo** [0e4ef622/wine-discord-ipc-bridge#10]
Hello thanks for this script but I'm very newestly and I need help. I trying install TruckersMP Launcher I installed and I start launcher but ''Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0'' error coming. I see your script but I'm newestly and I didn't how to use this script. Can you help me? I use Linux Mint 20 Cinnamon.

**Comment by 0e4ef622** [comment]
That message is not an error.

**Comment by xympo** [comment]
I want to use your program to solve this error, but I don't know how to use it
