### ISSUE TITLE
osu! with wine-discord-ipc-bridge

### ISSUE THREAD

**Issue by Polaczeq22** [0e4ef622/wine-discord-ipc-bridge#14]
Hi

I've just recently made file with wineprefix set on the same one as for osu! (installed via PlayOnLinux).
Launched executable for ipc bridge closes after launching osu!, but no Rich Presence is passed to Discord.

What should I do?

**Comment by nixls** [comment]
It doesn't close while launching osu! on my end (I use Lutris). Can you post the log? I don't know how it is on PlayOnLinux, but I had to launch winediscordipcbridge.exe manually from the terminal to obtain the log.

**Comment by Razuuu** [comment]
Hey @nixls can u show me how to do this with Lutris, idk how....

**Comment by Polaczeq22** [comment]
Sorry for inactivity
It turned out to work somehow at some point. 
I don't remember doing anything to make it running, it just started working by itself
