### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by LukeVader-IV** [0e4ef622/wine-discord-ipc-bridge#16]
initially I tired running the .exe and then running the game, it didn't do anything to my disocrd even though the .exe did recognise the game was running (I can no longer replicate it)

after I tried using the script in the github and (after my dubass figured out i had to add an argument like wine) i got an error

> ./winediscordipcbridge-steam.sh: line 18: runtimecmd: bad array subscript
>0104:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
>0104:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
>0104:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
>Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0
>CreateNamedPipe failed, GLE=231.
>Usage: wine PROGRAM [ARGUMENTS...]   Run the specified program
>       wine --help                   Display this help and exit
>       wine --version                Output version information and exit

OS: Fedora 33 linux 5.11 kernel

**Comment by 0e4ef622** [comment]
Most likely `GLE=231` means the bridge is already running, kill it and try again.

**Comment by LukeVader-IV** [comment]
all right, I started my pc up again so any process that would've been running weren't running anymore and it works again

however my discord status remains the same, AKA. empty, Has anyone actually tried this with rocket league?

It also launches a game twice now for some reason, i'm getting a little confused by the scrypt, are you supposed to run "./shellscript.sh wine [game]" ?

**Comment by chent7** [comment]
Run the bridge, wait for the bridge to start looling for a game (usually takes around 1 second), then run the game.
All using the same wine prefix.
Remember to kill the bridge after closing the game.
In some cases restarting discord helps, or use lightcord.

**Comment by LukeVader-IV** [comment]
Thanks for the help (:
