### ISSUE TITLE
Proton: Failed to execute child process "winediscordipcbridge.exe" (No such file or directory)

### ISSUE THREAD

**Issue by Waces** [0e4ef622/wine-discord-ipc-bridge#18]
I've cloned the repo, compiled the .exe with `make` and changed the run command on Steam to run the .sh
 
When trying to run, the bridge doesn't start, in the logs there's
`
pressure-vessel-adverb[93355]: E: Failed to execute child process "/home/geck0/app/wine-discord-ipc-bridge/winediscordipcbridge.exe" (No such file or directory)
`
Which means proton is running the script, but for some reason not finding/able to run the actual .exe

I've checked and rechecked the paths and tried absolute paths multiple times, but it doesn't work.

If I put `"${protoncmd[@]//run}" dir "path/to/wine-discord-ipc-bridge/"` in the script, on the logs it lists the contents of the folder.  
Or if I point `BRIDGE` to some arbitrary bash script, it will execute the script (though if I try to run the .exe from it, it still says 'not found').  
So Proton can see the files, but is giving the 'No such file or directory' specifically when trying to run the .exe

I don't know if it's some specific thing with Proton, that doesn't allow it to run external exes anymore or whatever. Tried a bunch of things for about tow hours, but nothing.

The game itself is still starting fine, but not the bridge.

Using Proton-6.16-GE-1

**Comment by 0e4ef622** [comment]
That's a Proton thing, it seems like the game is run inside of a container that has restricted access to files or something. The script is currently broken, I haven't found time nor motivation to fix it yet. If you want, you can look into [this fork](https://github.com/hitomi-team/discord-ipc-bridge) which seems to install the bridge into the wineprefix as a service.
