### ISSUE TITLE
Not working with subnautica below zero

### ISSUE THREAD

**Issue by NepNep21** [0e4ef622/wine-discord-ipc-bridge#20]
Well i have no idea if this will go anywhere but here it goes, currently i have the program being launched with `PROTON_REMOTE_DEBUG_CMD=$HOME/bin/wine-discord-ipc-bridge/winediscordipcbridge.exe PRESSURE_VESSEL_FILESYSTEMS_RW="/run/user/1000" PROTON_LOG=1 %command%`, tested with proton GE 6.21-2, proton 6.3-8, and proton 5.13-6, none worked, though the last 2 had this appear https://i.imgur.com/0WA9Xlk.png, which isn't RPC but might mean something, i also made my own small program to test that it wasn't an issue with the executable https://gist.github.com/NepNep21/d604abeb7e4c90a04e37f697d6f6fa11 and as i thought, that worked fine, meaning this is an issue with either the game, or how the program is being launched, after checking the proton log i can see that the program is started with the first 2 proton versions mentioned, but not the last, which is confirmed by the fact i had to manually stop the game on steam with those same 2 versions (since the game never connected to allow the program to automatically stop)

**Comment by NepNep21** [comment]
A few extra details i forgot to mention, i'm on arch, discord and steam are both installed through pacman, and a discord socket does exist at /run/user/1000/

**Comment by alwilson** [comment]
I don't think [PROTON_REMOTE_DEBUG_CMD](https://github.com/ValveSoftware/Proton/commit/5bc6cdaa8eb69fad8b0ddf7bef114bfe8ffae010) is an option on 5.13-6. I'm also running arch, discord and steam through pacman. I've only tried it with Deep Rock Galactic though. Is there anything on the command line if you start steam there? I noticed that's where the bridge dumps its output. I ended up adding some more debug to the bridge to print exit codes.

```
Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0
...
Client connected
Creating socket
Attempting to connect to /run/user/1000/discord-ipc-0
Connected successfully
48 bytes w->l
340 bytes l->w
73 bytes w->l
81 bytes l->w
```

**Comment by NepNep21** [comment]
I checked the proton log and there was the `Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0` message, but nothing from the bridge after that

**Comment by NepNep21** [comment]
Seems to not be a general issue as it works flawlessly in fallout 4 with a rich presence mod, going to close this then
![2022-07-03_20-17](https://user-images.githubusercontent.com/43792621/177060574-5f528b76-6e53-44d4-9988-71757f30db69.png)
