### ISSUE TITLE
Prevents Deep Rock Galactic from running

### ISSUE THREAD

**Issue by chowder3907** [0e4ef622/wine-discord-ipc-bridge#21]
Using this prevents DRG from opening. 
I'm running Manjaro KDE

`/bin/sh\0-c\0/home/noah/Other/wine-discord-ipc-bridge/winediscordipcbridge-steam.sh /home/noah/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=548430 -- '/home/noah/3TB/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/noah/.local/share/Steam/compatibilitytools.d/Proton-6.21-GE-2'/proton waitforexitandrun  '/home/noah/.local/share/Steam/steamapps/common/Deep Rock Galactic/FSD.exe' -nohmd\0
Game process added : AppID 548430 "/home/noah/Other/wine-discord-ipc-bridge/winediscordipcbridge-steam.sh /home/noah/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=548430 -- '/home/noah/3TB/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/noah/.local/share/Steam/compatibilitytools.d/Proton-6.21-GE-2'/proton waitforexitandrun  '/home/noah/.local/share/Steam/steamapps/common/Deep Rock Galactic/FSD.exe' -nohmd", ProcID 34841, IP 0.0.0.0:0
chdir /home/noah/.local/share/Steam/steamapps/common/Deep Rock Galactic
ERROR: ld.so: object '/home/noah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 548430, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/noah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/noah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 548430, ActionID 3] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/noah/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/noah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/noah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/noah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 34847 != 34844, skipping destruction (fork without exec?)
bwrap: Can't make symlink at /run/user/1000/pulse: File exists
Game process removed: AppID 548430 "/home/noah/Other/wine-discord-ipc-bridge/winediscordipcbridge-steam.sh /home/noah/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=548430 -- '/home/noah/3TB/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/noah/.local/share/Steam/compatibilitytools.d/Proton-6.21-GE-2'/proton waitforexitandrun  '/home/noah/.local/share/Steam/steamapps/common/Deep Rock Galactic/FSD.exe' -nohmd", ProcID 34841 
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.No cached sticky mapping in ActivateActionSet.
`

**Comment by MrSimbax** [comment]
Fedora 35 here, I have the same problem but I've found a workaround.

Set launch options for DRG as the following, launch it, and exit.

```
PROTON_DUMP_DEBUG_COMMANDS=1 PROTON_DEBUG_DIR=$HOME %command%
```

You should find a new directory `/home/$USER/proton_$USER` with a few scripts. Use the `run` script to run `winediscordipcbridge.exe`:

```
~/proton_$USER/run path/to/winediscordipcbridge.exe
```

Now run the game, also by using the script, but without any arguments.

```
~/proton_$USER/run
```

Unfortunately, you can't run the game directly from Steam because it now thinks the game is running even though it's really the `winediscordipcbridge.exe` running in the background. This also means no overlay in DRG.

Anyway, now you should be able to interact with the IMU terminal. It still asked me to join a union even though I was already in one, but after restarting the game it detected my membership correctly and I could claim the rewards. So it's as unstable as on Windows, therefore the bridge seems to be working correctly :D Thanks.

Since I'm using the Flatpak version of Discord, I also had to follow this [comment](https://github.com/0e4ef622/wine-discord-ipc-bridge/issues/17#issuecomment-982285675) and change the path from `/run/user/1000/discord-ipc-0` to `/run/user/1000/app/com.discordapp.Discord/discord-ipc-0`.

Hope that helps.

**Comment by chowder3907** [comment]
> Fedora 35 here, I have the same problem but I've found a workaround.
> 
> Set launch options for DRG as the following, launch it, and exit.
> 
> ```
> PROTON_DUMP_DEBUG_COMMANDS=1 PROTON_DEBUG_DIR=$HOME %command%
> ```
> 
> You should find a new directory `/home/$USER/proton_$USER` with a few scripts. Use the `run` script to run `winediscordipcbridge.exe`:
> 
> ```
> ~/proton_$USER/run path/to/winediscordipcbridge.exe
> ```
> 
> Now run the game, also by using the script, but without any arguments.
> 
> ```
> ~/proton_$USER/run
> ```
> 
> Unfortunately, you can't run the game directly from Steam because it now thinks the game is running even though it's really the `winediscordipcbridge.exe` running in the background. This also means no overlay in DRG.
> 
> Anyway, now you should be able to interact with the IMU terminal. It still asked me to join a union even though I was already in one, but after restarting the game it detected my membership correctly and I could claim the rewards. So it's as unstable as on Windows, therefore the bridge seems to be working correctly :D Thanks.
> 
> Since I'm using the Flatpak version of Discord, I also had to follow this [comment](https://github.com/0e4ef622/wine-discord-ipc-bridge/issues/17#issuecomment-982285675) and change the path from `/run/user/1000/discord-ipc-0` to `/run/user/1000/app/com.discordapp.Discord/discord-ipc-0`.
> 
> Hope that helps.

This worked perfectly, thanks!
