### ISSUE TITLE
Seems to stop after bridging a few times

### ISSUE THREAD

**Issue by Roadhog360** [0e4ef622/wine-discord-ipc-bridge#28]
Just open and close the same program two or three times over the span of a few minutes.

Bridging will then proceed to just fail.

**Comment by 0e4ef622** [comment]
Can you provide more details? I am unable to reproduce this.

**Comment by Roadhog360** [comment]
I really provided all of the details I can. I guess I could share the application, which is this. https://github.com/soopercool101/BrawlCrate

I told you the whole issue though. It seems it will only bridge very little before it stops working at all.

**Comment by Roadhog360** [comment]
I did not notice this bridges only one application at a time.

Is the issues page suitable for feature requests?

**Comment by SimonFoxcoon** [comment]
I've run into this issue, in general after a few times of using the bridge it just does not show rich presence on my profile anymore. I'm using foobar2000 in wine, with winegui, and i have the ipcbridge exe with the same prefix. I check System Monitor and it'll show up as a process. but right after I open fb2k and wait a second or two for library to load, then process disappears, without showing rich presence on my profile. It has worked before.
