### ISSUE TITLE
Doesn't work with PDRPC

### ISSUE THREAD

**Issue by Saraistupid** [0e4ef622/wine-discord-ipc-bridge#31]
Running wine-discord-ipc-bridge with Project Diva Megamix+ (with the PDRPC mod) doesn't pass the rpc status to Discord
PDRPC doesn't detect Discord
```
[PDRPC]: Waiting for Discord...
```
My launch options: `WINEDLLOVERRIDES='dinput8.dll=n,b' gamemoderun mangohud /home/e404nnf/wine-discord-ipc-bridge/winediscordipcbridge-steam.sh %command%`

**Comment by Saraistupid** [comment]
Solved it, if you have ShareDiva, uninstall it, then put the `winediscordipcbridge-steam.sh` right before `gamemoderun`, not right before `%command%`

**Comment by arianneorpilla** [comment]
Thanks, this helped me set up PDRPC on my Steam Deck. 

For anyone else that was explicitly looking for this, I placed `winediscordipcbridge-steam.sh` and the EXE in a folder in my home directory

The .sh file needed `chmod +x`, then I did: `WINEDLLOVERRIDES='dinput8.dll=n,b' <.sh location here> gamemoderun %command%`
