### ISSUE TITLE
Steam - rpc shows the right game for few secs than goes to wine64-preloader

### ISSUE THREAD

**Issue by Yaikava** [0e4ef622/wine-discord-ipc-bridge#36]
Launch command: `gamemoderun MANGOHUD=1 /opt/discord-ipc-bridge/winediscordipcbridge-steam.sh  %command%`
RPC is correct game at start for few seconds than it goes back to `wine64-preloader` and/or `pv-bwrap`.
Any clue why?
Testing it with dead by daylight.

**Comment by Yaikava** [comment]
![image](https://user-images.githubusercontent.com/83710104/236802335-b0589060-8b78-4ac3-811b-1d2c6fdb296e.png)
![image](https://user-images.githubusercontent.com/83710104/236802428-2b6b9840-11fc-4d52-b063-838c29de3c4a.png)

**Comment by 0e4ef622** [comment]
Is this actually rich presence, or just the basic game detection that discord does for every game?

**Comment by Yaikava** [comment]
I think it is basic. Is that a problem?

**Comment by 0e4ef622** [comment]
This project doesn't fix that, it's only for rich presence unfortunately.

**Comment by Yaikava** [comment]
Oh 😑
