### ISSUE TITLE
Issues with LoL and Lutris on Arch Linux

### ISSUE THREAD

**Issue by ZeroKun265** [0e4ef622/wine-discord-ipc-bridge#37]
I really hope i'm doing something wrong, but i have a wine prefix in ~/Games/league-of-legends that's using lutris-ge-lol 8.7.1
Now, what i did first is set it up to be launched as a pre-launch script, that didn't work. 
So i tried manuually, i opened up my shell and typed `WINEPREFIX=/home/zerokun265/Games/league-of-legends`, then i typed `/path/to/lutris-ge-lol8.7.1/bin/wine /home/zerokun265/Games/league-of-legends/winediscordipcbridge.exe` and this was the output i got before launching league
```
wineserver: using server-side synchronization.
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.7 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0
```

then i launched league but nothing new got printed and as expected, game was shown to be played but no rich presence

Then after that i tried opening the wine console from lutris, closed league, then typed `winediscordipcbridge.exe` and got this output 
```
Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0
```

Then i launched league of legends from lutris and once the game loaded i got this output
```
Client connected
Attempting to connect to (run(user/1000/discord-ipc-0
Connected succesfully
48 bytes W->1
365 bytes 1->W
61 bytes W->1
61 bytes W->1
65 bytes 1->W
61 bytes 1->W
```
And once again it sayd playing League of Legends with the icon but no rich presence

Am i doing something wrong here or what?

**Comment by 0e4ef622** [comment]
You might be seeing rich presence from Lutris itself, see if you can disable that. The `w->l`/`l->w` stuff is what you want to see, it means the bridge is working.

**Comment by ZeroKun265** [comment]
Welp, i ended up using [this](https://github.com/daglaroglou/league-rpc-linux) and it solved my issue, altouh the rpc isn't quite like the one from the official game but it's not a problem for me.
I don't know if you want to investigate more (i'm available if you need to) or just close this :)

**Comment by 0e4ef622** [comment]
It seems like this does work, just nothing happens until you actually get into a game.
