### ISSUE TITLE
Can't use it with proton

### ISSUE THREAD

**Issue by draxdeveloper** [0e4ef622/wine-discord-ipc-bridge#4]
I am trying to make the script work on proton, I followed the instruction in the .sh as in:
"# Set the game's launch options to: /path/to/this-script.sh %command%"
But when I do this steam opens  the script and the game don't launch. I imagine that it's because the command changes what will be launched and then it stops there. Thus, it would be needed a script that would also launch the game somehow, maybe we could just make a copy for each game? It's not the best solution but it's something

**Comment by 0e4ef622** [comment]
By default there's a 10 second delay between starting the bridge and starting the game, so maybe you didn't wait long enough?
