### ISSUE TITLE
Never connects to Discord

### ISSUE THREAD

**Issue by tdm4** [0e4ef622/wine-discord-ipc-bridge#43]
When I run  `winediscordipcbridge` in the same WINEPREFIX as my game (it's a 32-bit WINARCH), I get this message:

```
Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0
```

And... it never connects at all.

My Discord IPC socket file is in `/run/user/1000/discord-ipc-0`

I'm not running this in Steam, just a custom WINEPREFIX. Does the WINEPREFIX need a Z: drive set up pointing to /
because I removed that. Adding it back doesn't seem to help. 

Running strace on the wine winediscordipcbridge shows it reads in the bit about finding it from XDG_RUNTIME_DIR and /tmp but I guess it never finds the file. Is there something I need to pass to winediscordipcbridge so it can find it or is this a file access problem?

**Comment by 0e4ef622** [comment]
Is that the only message you get? Or are there more logs?

> Does the WINEPREFIX need a Z: drive set up pointing to /
because I removed that.

No

> Is there something I need to pass to winediscordipcbridge so it can find it or is this a file access problem?

Is the XDG_RUNTIME_DIR env var set? In your case it should be set to `/run/user/1000`.

**Comment by tdm4** [comment]
Yes, that is the only message I get. No other logs. 

```
$ echo $XDG_RUNTIME_DIR
/run/user/1000
```

Running on WINE 9.17.

**Comment by 0e4ef622** [comment]
So it's the game that's not connecting to the pipe, are you sure the game supports rich presence?

# Rich presence
![image](https://github.com/0e4ef622/wine-discord-ipc-bridge/assets/8326135/027a7e26-7d4c-4911-85ac-188db2662be4)
![image](https://github.com/0e4ef622/wine-discord-ipc-bridge/assets/8326135/26d2213d-cd2d-4079-8972-508657ca5501)

# Not rich presence
![image](https://github.com/0e4ef622/wine-discord-ipc-bridge/assets/8326135/5d64bb76-e219-4273-b316-b8760e696e97)
