### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Lucki** [0e4ef622/wine-discord-ipc-bridge#6]
This project is missing a license which makes it clear what usage is allowed and forbidden.

Also you've mentioned that you want to include this in wine: Is there a ticket I can follow?

**Comment by 0e4ef622** [comment]
Thanks, I've added a license. And no, I haven't made a ticket on wine.

**Comment by Lucki** [comment]
Thank you!

> I haven't made a ticket on wine.

Please let me know when there's some progress going on.

> I've only tested this with osu! on Arch Linux with a 32-bit wineprefix.

We've included this in https://github.com/lhark/truckersmp-cli so we can confirm this is working for TruckersMP in a 64-bit wineprefix.

**Comment by 0e4ef622** [comment]
> Please let me know when there's some progress going on.

[I opened a ticket](https://bugs.winehq.org/show_bug.cgi?id=50045), let's see if it goes anywhere :P.

I've also uploaded a stripped binary which is much smaller.

**Comment by samip5** [comment]
Ah, I see that there are comments on the wine ticket, and you also commented on the Valve proton issue about Discord support. :)
