### ISSUE TITLE
Steam game won't launch

### ISSUE THREAD

**Issue by Waces** [0e4ef622/wine-discord-ipc-bridge#8]
Trying to use it with Proton for some games

Followed the instruction and put the `path/to/winediscordipcbridge-steam.sh %command%`, and had `BRIDGE=path/to/winediscordipcbridge.exe` in the .sh, with both being absolute paths

The game will simply not launch, it will say that it's running for a few seconds then close

When seeing trough the logs (running steam trough terminal), this is something appeared that I think could relate:
`pressure-vessel-adverb[955239]: Failed to execute child process "run" (No such file or directory)`

**Comment by 0e4ef622** [comment]
Seems like Steam changed how it launches games with Proton. I'll have to edit the script to accommodate this. Previously, the command run would look like this:
```
/mnt/hdd/SteamLibrary/steamapps/common/Proton 5.13/proton waitforexitandrun /mnt/hdd/SteamLibrary/steamapps/common/Muse Dash/MuseDash.exe
```
Now, it looks like this:
```
/mnt/hdd/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --deploy=soldier --suite=soldier --verb=waitforexitandrun -- /mnt/hdd/SteamLibrary/steamapps/common/Proton 5.13/proton waitforexitandrun /mnt/hdd/SteamLibrary/steamapps/common/Muse Dash/MuseDash.exe
```

**Comment by 0e4ef622** [comment]
Hm, so if I understand correctly, the new way runs the game in a container, which means I can't access Discord's IPC socket. For now, here's a script that works by just cutting out the container stuff, although I wouldn't be surprised if it breaks again soon.

```bash
#!/bin/sh

# Run a Steam Play game with wine-discord-ipc-bridge
# Set the game's launch option to: path/to/this-script.sh %command%

BRIDGE="/path/to/winediscordipcbridge.exe"
DELAY=1

runtimecmd=()
protoncmd=()
for arg in "$@"; do
    if [ "${runtimecmd[-1]}" == "--" ]; then
        protoncmd+=("$arg");
    else
        runtimecmd+=("$arg");
    fi
done

gamecmd=("${protoncmd[@]:2}")
protoncmd=("${protoncmd[@]:0:2}")

"${protoncmd[@]}" "$BRIDGE" &
sleep $DELAY
"${protoncmd[@]//waitforexitandrun/run}" "${gamecmd[@]}"
```

If anyone else wants to try making it work with the containers, here's a version that tries to run the bridge in it.
```bash
#!/bin/sh

# Run a Steam Play game with wine-discord-ipc-bridge
# Set the game's launch option to: path/to/this-script.sh %command%

BRIDGE="/path/to/winediscordipcbridge.exe"
DELAY=1

runtimecmd=()
protoncmd=()
for arg in "$@"; do
    if [ "${runtimecmd[-1]}" == "--" ]; then
        protoncmd+=(\""$arg"\");
    else
        runtimecmd+=("$arg");
    fi
done

gamecmd=("${protoncmd[@]:2}")
protoncmd=("${protoncmd[@]:0:2}")
cmd="${protoncmd[@]} \"$BRIDGE\" & sleep $DELAY; ${protoncmd[@]//waitforexitandrun/run} ${gamecmd[@]}"

"${runtimecmd[@]}" bash -c "$cmd"
```

**Comment by Waces** [comment]
Without the container it seems to work.

Though I wonder if there would be some way to sign certain passtroughs in the container?
