### ISSUE TITLE
How to set it to run in a specific wine prefix?

### ISSUE THREAD

**Issue by HK0811** [0e4ef622/wine-discord-ipc-bridge#9]
I installed osu with lutris in /home/user/Games/osu
but wine discord ipc bridge is running in /home/user/.wine
So wine discord ipc bridge can't detect osu running (of course)
Is there any way to set wine discord ipc bridge to run in the osu wine prefix instead of the default wine prefix?
Or I must install osu in the default wine prefix?

**Comment by 0e4ef622** [comment]
Use the `WINEPREFIX` environment variable.
